# Generated by Django 5.2 on 2025-05-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('a', 'Applied'), ('i', 'Interview'), ('o', 'Offer'), ('r', 'Rejected'), ('ach', 'Achieved')], default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobtracker.position'),
        ),
    ]
