# Generated by Django 5.2 on 2025-05-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0002_remove_status_name_status_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('a', 'Applied'), ('i', 'Interview'), ('o', 'Offer'), ('r', 'Rejected'), ('ach', 'Achieved')], default='a', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobtracker.website'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobtracker.website'),
        ),
    ]
