# Generated by Django 5.2 on 2025-05-13 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0004_jobapplication_expected_ans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='expected_ans',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
