# Generated by Django 5.2 on 2025-05-15 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0005_remove_jobapplication_expected_ans_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-date_applied'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['name'], 'verbose_name': 'Job Type', 'verbose_name_plural': 'Job Types'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='wage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Salary'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobtracker.website'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('user', 'company', 'position')},
        ),
    ]
