# Generated by Django 5.2 on 2025-05-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0006_alter_company_options_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='website',
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobtracker.website'),
        ),
    ]
