# Generated by Django 5.2 on 2025-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0008_alter_company_location_alter_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='JobType'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position'),
        ),
    ]
